import Config

# Local icon storage for development
config :fluentui_icons, icons_path: Path.expand("../.icons", __DIR__)

# Configure your database - uses environment variables with defaults for local dev
config :fluentui_icons, FluentuiIcons.Repo,
  username: System.get_env("DB_USERNAME") || "fluentui_icons",
  password: System.get_env("DB_PASSWORD") || "fluentui_icons",
  hostname: System.get_env("DB_HOSTNAME") || "db-01.km8.local",
  database: System.get_env("DB_DATABASE") || "fluentui_icons",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :fluentui_icons, FluentuiIconsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "L44M6AEaNldcCAei0vVvUpTDWhJwggMFCB+a1Lz3TeucpwXx29AGFpssbR+fTwSc",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :fluentui_icons, FluentuiIconsWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/fluentui_icons_web/(live|views)/.*(ex)$",
      ~r"lib/fluentui_icons_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Import local config if it exists (for user-specific overrides)
if File.exists?(Path.expand(".local.exs", __DIR__)) do
  import_config ".local.exs"
end
